### ISSUE TITLE
mvn package failed with error

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/guide-microprofile-config#7] opened 2017-11-16 11:32 UTC
Running "mvn install" to build and package the defaultServer and application successfully. My understanding is to use "mvn package" to build the changes when the server and application are running. When I ran "mvn package" the command failed complaining that the server must be stopped first.

[INFO] Packaging server defaultServer.
[INFO] Server defaultServer is running.
[INFO] Server defaultServer package failed. It must be stopped before it can be packaged.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.650 s
[INFO] Finished at: 2017-11-16T05:23:45-06:00
[INFO] Final Memory: 18M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.0:package-server (package-app) on project io.openliberty.guides.microprofile.mpconfig: CWWKM2002E: Failed to invoke [/Users/lavena/Downloads/guide-microprofile-config-master/finish/target/liberty/wlp/bin/server, package, defaultServer, --archive=/Users/lavena/Downloads/guide-microprofile-config-master/finish/target/LibertyProject.zip, --include=usr]. RC= 3 but expected=[0]. -> [Help 1]

**Comment by evelinec** [comment] 2017-11-17 03:50
This does looks like a problem. I tried the sequence of commands on multiple guides, they all have the problem. This needs to be fixed in the mvnbuild.adoc under guides-common.

**Comment by evelinec** [comment] 2017-11-17 05:09
While looking into this further, looks like it's rather a problem in the pom.xml file for some of the guides. Will work with Junyi on it.

**Comment by yeekangc** [comment] 2017-11-17 14:12
If we need to fix mvnbuild.adoc, let us do this and open a new issue under guides-common.  The same for the other guides.  We can use the current one for MP Config as a starting point to figure out the proper solution and then, propagate to other guides.

**Comment by JunyiSun** [comment] 2017-11-17 15:44
@evelinec Thank you for your investigation!  
I will start to compare the pom.xml files between this guide and others. And we can propagate the fix to other guides later on.

**Comment by JunyiSun** [comment] 2017-11-17 20:47
I found that the problem is caused by missing some configuration in the pom.xml file. 
```
             <goals>
                <goal>package-server</goal>
              </goals>
         //this part is missing in pom.xml files for some guides, need to be added
             <configuration>
               <outputDirectory>target/wlp-package</outputDirectory>
             </configuration>
           
```

**Comment by JunyiSun** [comment] 2017-11-17 20:48
@lavenal  The problem is fixed for this guide. Please check the latest code again. Thank you!

**Comment by yeekangc** [comment] 2017-11-17 22:10
@JunyiSun, once we have confirmation on the fix, let us open new issues to propagate the fix across.  Thank you.

**Comment by JunyiSun** [comment] 2017-11-17 22:15
@yeekangc Yes I will do that later on.

**Comment by JunyiSun** [comment] 2017-11-17 22:49
Lavena agrees to close this issue. Thank you.

**Closed by JunyiSun** 2017-11-17 22:49 UTC
